# Generated by Django 3.1.3 on 2021-01-17 01:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomination_form', '__first__'),
        ('student', '__first__'),
        ('theory', '__first__'),
        ('answer', '0001_initial'),
        ('question', '__first__'),
        ('result', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('exam_slug', models.CharField(default='no slug', max_length=500)),
                ('exam_type', models.CharField(max_length=500)),
                ('batch', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=500)),
                ('total_score', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTheoryConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.theory')),
            ],
        ),
        migrations.CreateModel(
            name='ExamStudentConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResultConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='result.result')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamNominationFormConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('nomination_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomination_form.nominationform')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswerConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answer.answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='answers',
            field=models.ManyToManyField(through='exam.ExamAnswerConnector', to='answer.Answer'),
        ),
        migrations.AddField(
            model_name='exam',
            name='nomination_forms',
            field=models.ManyToManyField(through='exam.ExamNominationFormConnector', to='nomination_form.NominationForm'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(through='exam.ExamQuestionConnector', to='question.Question'),
        ),
        migrations.AddField(
            model_name='exam',
            name='results',
            field=models.ManyToManyField(through='exam.ExamResultConnector', to='result.Result'),
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(through='exam.ExamStudentConnector', to='student.Student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='theorys',
            field=models.ManyToManyField(through='exam.ExamTheoryConnector', to='theory.Theory'),
        ),
    ]
