# Generated by Django 3.1.3 on 2021-01-17 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NominationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_one', models.CharField(max_length=100)),
                ('phone_one', models.CharField(max_length=100)),
                ('qualification_one', models.TextField()),
                ('residental_state_one', models.CharField(max_length=100)),
                ('name_two', models.CharField(max_length=100)),
                ('phone_two', models.CharField(max_length=100)),
                ('qualification_two', models.TextField()),
                ('residental_state_two', models.CharField(max_length=100)),
                ('name_three', models.CharField(max_length=100)),
                ('phone_three', models.CharField(max_length=100)),
                ('qualification_three', models.TextField()),
                ('residental_state_three', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
